[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "project-tic-tac-toe"
version = "0.1.0"
[tool.poetry.dependencies]
maya = "^0.6.1"
python = "^3.8"
[tool.poetry.dev-dependencies]
